version: "3.7"

services:
  verdaccio:
    container_name: "verdaccio"
    image: verdaccio/verdaccio:3.0.0
    restart: always
    ports:
      - "4873:4873"
    # volumes:
    #   - ./data:/verdaccio/
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
