version: "3.7"

services:
  verdaccio:
    container_name: "verdaccio"
    image: verdaccio/verdaccio
    restart: always
    ports:
      - "4873:4873"
    volumes:
      - "./volumes/verdaccio/storage:/verdaccio/storage"
      - "./volumes/verdaccio/conf:/verdaccio/conf"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
